### ISSUE TITLE
Build failed: plotlabserver

### ISSUE THREAD

**Issue by daniel-gitgit** [eclipse-adore/adore_ROS1#51] opened 2022-11-11 11:56 UTC
Andrew?

Using this hash: 
- https://github.com/eclipse/adore/commit/7e37327c82a78f1c2accbc98c61a2600e2a5fb8e
- which refers to https://github.com/dlr-ts/plotlabserver/tree/4bd9214b2a8e6d23ca8ea0d60d1fbe26f9a7e8b2

Problem:
- docker-compose.yaml is missing entry ```network_mode: "host"```

Pls PR to https://github.com/eclipse/adore/tree/dev_v0.3.2_bs

**Comment by akoerner1** [comment] 2022-12-01 12:54
The root cause of this failure is that apt-cacher-ng must be running during build of plotlabserver.  Depending on invocation order this may not be the case.  This resolved in [PR#52](https://github.com/eclipse/adore/pull/52)

This issue can be closed.

**Closed as completed** 2023-07-19 11:08 UTC
